services:
  #  order-service:
  #    image: order-service:latest
  #    build: order-service
  #    restart: "no"
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - postgres
  #  restaurant-service:
  #    image: restaurant-service:latest
  #    build: restaurant-service
  #    restart: "no"
  #    ports:
  #      - "8081:8080"
  #    depends_on:
  #      - postgres
  #  user-service:
  #    image: user-service:latest
  #    build: user-service
  #    restart: "no"
  #    ports:
  #      - "8082:8080"
  #    depends_on:
  #      - postgres
  postgres:
    image: postgres:16.0
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eats
      TZ: Europe/Moscow
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgres
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres:5432/eats
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
  pgadmin:
    image: dpage/pgadmin4:8.13.0
    restart: "no"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
      - ./docker/pgadmin/pgpass:/pgadmin4/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: stukenvitalii@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/misc/ping || exit -1
      interval: 10s
      timeout: 5s

      start_period: 10s
      retries: 5
    depends_on:
      - postgres
    entrypoint: /bin/sh -c "chmod 600 /pgadmin4/pgpass; /entrypoint.sh;"

volumes:
  postgres_data:
  pgadmin_data: