app:
  secret-key: ${SECRET}
  user-service-url: http://localhost:8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**
        - id: restaurant-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/restaurants/**
