app:
  secret-key: ${SECRET}
  user-service-url: http://localhost:8081

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/rest/users
          predicates:
            - Path=/rest/users/**
          filters:
            - name: Jwt
        - id: order-service
          uri: http://localhost:8082/rest/orders
          predicates:
            - Path=/rest/orders/**
          filters:
            - name: Jwt
        - id: restaurant-service
          uri: http://localhost:8083/rest/restaurants
          predicates:
            - Path=/rest/restaurants/**
          filters:
            - name: Jwt
        - id: restaurant-service-dishes
          uri: http://localhost:8083/rest/dishes
          predicates:
            - Path=/rest/dishes/**
          filters:
            - RewritePath=/rest/dishes/(?<segment>.*), /rest/dishes/${segment}
            - name: Jwt
  main:
    web-application-type: reactive
debug: on

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
