app:
  user-service-url: https://localhost:8081
  restaurant-service-url: https://localhost:8082
server:
  port: 8080
spring:
  application:
    name: order-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/eats
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
