app:
  restaurant-service-url: http://localhost:8083
server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/eats
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  jackson:
    time-zone: Europe/Moscow
