app:
  order-service-url: https://localhost:8082
  user-service-url: https://localhost:8081

server:
  port: 8083

spring:
  application:
    name: restaurant-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/eats
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
